# Permalinks
#
permalink:           pretty

# Setup
title:               suhas2go
tagline:             'What the magic of free time can do'
description:         'Mathematics Undergrad <br /> IIT Guwahati'
url:                 http://suhas2go.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Suhas Nayak
  url:               https://twitter.com/coutsuhas
  email:             suhas2go@gmail.com
  github:            suhas2go
  linkedin:          nsuhas  
  stackoverflow_id:  6493646  
  email_md5:         57bee3d648e25717b65b14930844cc23                    

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]

github repo:          https://github.com/suhas2go/suhas2go.github.io

# Google Analytics
google_analytics: UA-105698961-1
